version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: docker/released/Dockerfile
    image: fm:latest
    environment:
      - DJANGO_SECRET_KEY
    command: finitelycomputable-django-apps run 0.0.0.0:8000
    ports:
      - "8000:8000"
